export const Data = [
  {
    id: 1,
    name: "Chain",
    price: 600,
    description: "Durable bike chain for mountain and road bikes.",
    stock: 15,
    image_url: "./chain.jpg",
  },
  {
    id: 2,
    name: "Brakes",
    price: 450,
    description: "Hydraulic disc brakes for better stopping power.",
    stock: 8,
    image_url: "./brake.jpg",
  },
  {
    id: 3,
    name: "Handlebar",
    price: 1500,
    description: "Ergonomic handlebar for better grip and comfort.",
    stock: 12,
    image_url: "./handle.jpeg",
  },
  {
    id: 4,
    name: "Pedals",
    price: 350,
    description: "Anti-slip pedals with reflectors for safety.",
    stock: 20,
    image_url: "./pedals.jpg",
  },
  {
    id: 5,
    name: "Saddle",
    price: 700,
    description: "Comfortable saddle for long rides.",
    stock: 10,
    image_url: "./seat.jpeg",
  },
  {
    id: 6,
    name: "Tires",
    price: 2500,
    description: "All-terrain tires for better grip.",
    stock: 18,
    image_url: "./tires.jpeg",
  },
  {
    id: 7,
    name: "Rims",
    price: 5000,
    description: "Lightweight aluminum rims.",
    stock: 7,
    image_url: "./rims.jpeg",
  },
  {
    id: 8,
    name: "Spokes",
    price: 1300,
    description: "Stainless steel spokes for strength and durability.",
    stock: 30,
    image_url: "./spokes.jpeg",
  },
  {
    id: 9,
    name: "Crankset",
    price: 800,
    description: "High-quality crankset for efficient pedaling.",
    stock: 5,
    image_url: "./Crankset.jpeg",
  },
  {
    id: 10,
    name: "Cassette",
    price: 1700,
    description: "Multi-speed cassette for easy shifting.",
    stock: 11,
    image_url: "./Cassette.jpg",
  },
  {
    id: 11,
    name: "Derailleur",
    price: 950,
    description: "Smooth shifting derailleur for precise gear changes.",
    stock: 9,
    image_url: "./Derailleur.jpeg",
  },
  {
    id: 12,
    name: "Seat Post",
    price: 550,
    description: "Adjustable seat post for customized seating height.",
    stock: 14,
    image_url: "./seat post.jpeg",
  },
];
