export const Data = [
  {
    id: 1,
    name: "Chain",
    price: 29.99,
    description: "Durable bike chain for mountain and road bikes.",
    stock: 15,
    image_url: "./bike1.jpg",
  },
  {
    id: 2,
    name: "Brakes",
    price: 45.99,
    description: "Hydraulic disc brakes for better stopping power.",
    stock: 8,
    image_url: "./bike1.jpg",
  },
  {
    id: 3,
    name: "Handlebar",
    price: 20.99,
    description: "Ergonomic handlebar for better grip and comfort.",
    stock: 12,
    image_url: "./bike1.jpg",
  },
  {
    id: 4,
    name: "Pedals",
    price: 19.99,
    description: "Anti-slip pedals with reflectors for safety.",
    stock: 20,
    image_url: "./bike1.jpg",
  },
  {
    id: 5,
    name: "Saddle",
    price: 35.99,
    description: "Comfortable saddle for long rides.",
    stock: 10,
    image_url: "./bike1.jpg",
  },
  {
    id: 6,
    name: "Tires",
    price: 30.99,
    description: "All-terrain tires for better grip.",
    stock: 18,
    image_url: "./bike1.jpg",
  },
  {
    id: 7,
    name: "Rims",
    price: 40.99,
    description: "Lightweight aluminum rims.",
    stock: 7,
    image_url: "./bike1.jpg",
  },
  {
    id: 8,
    name: "Spokes",
    price: 10.99,
    description: "Stainless steel spokes for strength and durability.",
    stock: 30,
    image_url: "./bike1.jpg",
  },
  {
    id: 9,
    name: "Crankset",
    price: 50.99,
    description: "High-quality crankset for efficient pedaling.",
    stock: 5,
    image_url: "./bike1.jpg",
  },
  {
    id: 10,
    name: "Cassette",
    price: 32.99,
    description: "Multi-speed cassette for easy shifting.",
    stock: 11,
    image_url: "./bike1.jpg",
  },
  {
    id: 11,
    name: "Derailleur",
    price: 45.0,
    description: "Smooth shifting derailleur for precise gear changes.",
    stock: 9,
    image_url: "./bike1.jpg",
  },
  {
    id: 12,
    name: "Seat Post",
    price: 15.99,
    description: "Adjustable seat post for customized seating height.",
    stock: 14,
    image_url: "./bike1.jpg",
  },
];
